#cloud-config
# vim: syntax=yaml
#
# Install Ansible from EPEL and Upstream version of Packer from the Hashicorps's RPM repo.
#
package_update: true
package_upgrade: true
package_reboot_if_required: true

yum_repos:
  hashicorp:
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    name: Hashicorp Stable - $basearch
    gpgcheck: 1
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    enabled: true
    # any repository configuration options (see man yum.conf)

packages:
  - ansible-core
  - packer
  - tmux
  - git-core

runcmd:
  - [ ln, -s, "/usr/bin/packer", "/usr/bin/packer.io" ]
  - [ sudo, -u, ec2-user, git, clone, "https://github.com/AlmaLinux/cloud-images.git", "/home/ec2-user/cloud-images" ]
