---
- name: Configure cloud-init Azure datasource
  ansible.builtin.copy:
    src: 91-azure_datasource.cfg
    dest: /etc/cloud/cloud.cfg.d/91-azure_datasource.cfg
    owner: root
    group: root
    mode: 0644

- name: Enable Hyper-V telemetry logging
  ansible.builtin.copy:
    src: 10-azure-kvp.cfg
    dest: /etc/cloud/cloud.cfg.d/10-azure-kvp.cfg
    owner: root
    group: root
    mode: 0644
