galaxy_info:
  role_name: qemu_guest
  author: Elkhan Mammadli
  description: Installs qemu-guest-agent and rsync
  license: MIT
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - 8
  galaxy_tags:
    - guest
    - system
    - qemu

dependencies: []
