---
# tasks file for preparing the system for AWS and install guest tools
- name: Remove firewall and linux-firmware
  ansible.builtin.command:
    argv:
      - dnf
      - -y
      - --installroot=/rootfs
      - --nogpgcheck
      - remove
      - firewalld
      - firewalld-filesystem
      - ipset
      - ipset-libs
      - iptables
      - python3-firewall
      - python3-slip
      - libnftnl
      - libnfnetlink
      - linux-firmware
  changed_when: true

- name: Find persistent-net.rules
  ansible.builtin.find:
    paths: /rootfs/etc/udev/rules.d
    patterns: 70*
  register: net_rules

- name: Delete persistent-net.rules
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ net_rules.files }}"

- name: Configure /etc/sysconfig/network
  ansible.builtin.lineinfile:
    path: /rootfs/etc/sysconfig/network
    line: "{{ item }}"
    create: true
  with_items:
    - NETWORKING=yes
    - NOZEROCONF=yes

- name: Create network-scripts folder
  ansible.builtin.file:
    path: /rootfs/etc/sysconfig/network-scripts
    state: directory

- name: Configure /etc/sysconfig/network-scripts/ifcfg-eth0
  ansible.builtin.copy:
    src: files/ifcfg-eth0
    dest: /rootfs/etc/sysconfig/network-scripts/ifcfg-eth0
    owner: root
    group: root
    mode: 0644

- name: Disable consistent network device naming
  ansible.builtin.file:
    src: /dev/null
    dest: /rootfs/etc/udev/rules.d/80-net-name-slot.rules
    owner: root
    group: root
    state: link

- name: Blacklist nouveau kernel module
  ansible.builtin.lineinfile:
    path: /rootfs/etc/modprobe.d/blacklist-nouveau.conf
    line: blacklist nouveau
    create: true
    owner: root
    group: root
    mode: 0644

- name: Disable firstboot
  ansible.builtin.lineinfile:
    path: /rootfs/etc/sysconfig/firstboot
    line: RUN_FIRSTBOOT=NO
    create: true
    owner: root
    group: root
    mode: 0644

- name: Disable root login
  ansible.builtin.command: "{{ item }}"
  loop:
    - chroot /rootfs passwd -d root
    - chroot /rootfs passwd -l root
  changed_when: true

- name: Add Amazon Time Sync Service to chrony config
  ansible.builtin.lineinfile:
    path: /rootfs/etc/chrony.conf
    line: "{{ item }}"
  with_items:
    - '# Amazon Time Sync Service'
    - 'server 169.254.169.123 prefer iburst'

- name: Disable virtual terminals allocation by logind
  ansible.builtin.replace:
    dest: "/rootfs/etc/systemd/logind.conf"
    regexp: '^#?NAutoVTs=\d+'
    replace: 'NAutoVTs=0'

- name: Install additional software
  ansible.builtin.command:
    argv:
      - dnf
      - -y
      - --installroot=/rootfs
      - --nogpgcheck
      - install
      - cloud-init
      - cloud-utils-growpart
      - dracut-config-generic
      - gdisk
      - rsync
      - tar
      - qemu-guest-agent
      - tuned
  changed_when: true

- name: Install AWS Systems Manager Agent (SSM Agent)
  ansible.builtin.dnf:
    installroot: "/rootfs"
    disable_gpg_check: true
    name: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
    state: present

- name: configure NetworkManager in cloud
  ansible.builtin.file:
    path: /rootfs/etc/systemd/system/nm-cloud-setup.service.d
    state: directory

- name: Setting NM Cloud provider to AWS
  ansible.builtin.lineinfile:
    path: /rootfs/etc/systemd/system/nm-cloud-setup.service.d/10-enable-ec2.conf
    line: "{{ item }}"
    create: true
  with_items:
    - '[Service]'
    - Environment=NM_CLOUD_SETUP_EC2=yes

- name: Configure NetworkManager default DHCP timeout
  community.general.ini_file:
    path: /rootfs/etc/NetworkManager/conf.d/dhcp.conf
    section: connection
    option: ipv4.dhcp-timeout
    value: 300
    owner: root
    group: root
    mode: 0644
    seuser: system_u

- name: Disable SSH password authentication
  ansible.builtin.lineinfile:
    path: /rootfs/etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: "sshd -T -f %s"
  loop:
    - regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication no'
    - regexp: '^ChallengeResponseAuthentication'
      line: 'ChallengeResponseAuthentication no'

- name: Enable openssh-server cloud-init amazon-ssm-agent services
  ansible.builtin.command: chroot /rootfs systemctl enable {{ item }}
  changed_when: true
  loop:
    - nm-cloud-setup.service
    - nm-cloud-setup.timer
    - sshd
    - chronyd
    - cloud-config
    - cloud-init
    - cloud-init-local
    - cloud-final
    - amazon-ssm-agent

- name: Change cloud-init user to ec2-user
  ansible.builtin.replace:
    dest: /rootfs/etc/cloud/cloud.cfg
    regexp: '^(\s+name:).*$'
    replace: '\1 ec2-user'

- name: Set virtual-guest as default profile for tuned
  ansible.builtin.lineinfile:
    path: /rootfs/etc/tuned/active_profile
    line: virtual-guest
    create: true

- name: Enable sgdisk in dracut
  ansible.builtin.lineinfile:
    path: /rootfs/etc/dracut.conf.d/sgdisk.conf
    line: 'install_items+=" sgdisk "'
    create: true
    owner: root
    group: root
    mode: 0644

- name: Enable Xen and NVME drivers
  ansible.builtin.lineinfile:
    path: /rootfs/etc/dracut.conf.d/ec2.conf
    line: 'add_drivers+=" nvme xen-netfront xen-blkfront "'
    create: true
    owner: root
    group: root
    mode: 0644

- name: Upgrade initramfs
  ansible.builtin.command: chroot /rootfs dracut -f --regenerate-all
  changed_when: true
