---
# tasks file for configuring bootloader
- name: Configuring GRUB default settings
  copy:
    src: grub
    dest: /rootfs/etc/default/grub
    mode: 0644

- name: Install GRUB for BIOS
  command: chroot /rootfs grub2-install --target=i386-pc /dev/nvme1n1

- name: Generate the GRUB configuration file
  command: chroot /rootfs grub2-mkconfig -o /boot/grub2/grub.cfg

- name: Enable OS Probe again
  ansible.builtin.lineinfile:
    path: /rootfs/etc/default/grub
    regexp: 'GRUB_DISABLE_OS_PROBER.*'
    state: absent
