---
# tasks file for configuring bootloader
- name: Configuring GRUB default settings
  ansible.builtin.copy:
    src: grub
    dest: /rootfs/etc/default/grub
    mode: 0644

- name: Install GRUB for BIOS
  ansible.builtin.command: chroot /rootfs grub2-install --target=i386-pc /dev/nvme1n1
  changed_when: true

- name: Generate the GRUB configuration file
  ansible.builtin.command: chroot /rootfs grub2-mkconfig -o /boot/grub2/grub.cfg
  changed_when: true

- name: Enable OS Probe again
  ansible.builtin.lineinfile:
    path: /rootfs/etc/default/grub
    regexp: 'GRUB_DISABLE_OS_PROBER.*'
    state: absent
