---
# tasks file for crearting partition table, partitions and format community.general.filesystem
- name: Gather disk information
  ansible.builtin.command: parted /dev/nvme1n1 unit MiB print
  changed_when: true
  register: parted_output

- name: Show disk information before the operations
  ansible.builtin.debug:
    var: parted_output.stdout_lines

- name: Create GPT Partition Table
  ansible.builtin.command: parted -s -a optimal /dev/nvme1n1 -- mklabel gpt
  changed_when: true

- name: Create BIOS boot partition
  ansible.builtin.command: parted -s -a optimal /dev/nvme1n1 -- mkpart biosboot 0% 2MiB set 1 bios_grub on
  changed_when: true

- name: Create Root Partition
  ansible.builtin.command: parted -s -a optimal /dev/nvme1n1 -- mkpart root xfs 2MiB 100%
  changed_when: true

- name: Format Root partition as XFS
  community.general.filesystem:
    dev: "/dev/nvme1n1p2"
    fstype: xfs
    state: present

- name: Gather disk information
  ansible.builtin.command: parted /dev/nvme1n1 unit MiB print
  changed_when: false
  register: parted_output

- name: Show disk information after the operations
  ansible.builtin.debug:
    var: parted_output.stdout_lines

- name: Get UUID of Root
  ansible.builtin.command: blkid /dev/nvme1n1p2 -s UUID -o value
  register: root_uuid
  changed_when: false
