---
- name: Installing the system release files
  command: rpm --root=/rootfs --nodeps -ivh https://repo.almalinux.org/almalinux/almalinux-release-latest-9.x86_64.rpm

- name: Installing the system GPG keys
  command: rpm --root=/rootfs --nodeps -ivh https://repo.almalinux.org/almalinux/almalinux-gpg-keys-latest-9.x86_64.rpm

- name: Installing the system repos
  command: rpm --root=/rootfs --nodeps -ivh https://repo.almalinux.org/almalinux/almalinux-repos-latest-9.x86_64.rpm

- name: Update the system
  command: dnf -y --installroot=/rootfs --nogpgcheck upgrade

- name: Creating fstab
  template:
    src: templates/fstab.j2
    dest: /rootfs/etc/fstab
    mode: 0644

- name: Install Base System on chroot
  shell: >
    dnf -y --installroot=/rootfs --nogpgcheck install
    kernel-core dracut-config-generic grub2-pc chrony dhcp-client
    rng-tools NetworkManager-cloud-setup
    @core
    --exclude="kexec-tools"
    --exclude="biosdevname"
    --exclude="open-vm-tools"
    --exclude="rhn*"
    --exclude="iprutils"
    --exclude="iwl*-firmware"
    --exclude="dnf-plugin-spacewalk"
    --exclude="plymouth*"
    --exclude="dracut-config-rescue"
    --exclude="mdadm"
    --exclude="langpacks-*"

- name: Make sure RPM using SQLite backend
  ansible.builtin.command: rpm --root=/rootfs -E "%{_db_backend}"
  register: rpm_db_backend
  failed_when: "rpm_db_backend.stdout != 'sqlite'"

- name: Set default target/runlevel and disable tmp.mount
  command: chroot /rootfs systemctl {{ item.cmd }} {{ item.unit }}
  loop:
    - { cmd: "set-default", unit: "multi-user.target" }
    - { cmd: "mask", unit: "tmp.mount" }

- name: Set default locale to C.UTF-8
  copy:
    content: LANG=C.UTF-8
    dest: /rootfs/etc/locale.conf
