---
# tasks file for install and relabel selinux
- name: relabel the filesystem 1/2
  ansible.builtin.file:
    force: true
    path: /rootfs/.autorelabel
    state: absent

- name: relabel the filesystem 2/2
  ansible.builtin.command: chroot /rootfs /sbin/fixfiles -f -F relabel
  changed_when: true

- name: Install SELinux
  ansible.builtin.command: dnf --installroot=/rootfs --nogpgcheck -y reinstall selinux-policy-targeted policycoreutils
  args:
    warn: false
  changed_when: true
