---
- name: Enable opennebula-addons repositroy
  dnf:
    name: almalinux-release-opennebula-addons
    state: present

- name: Install OpenNebula Linux VM Contextualization
  dnf:
    name: one-context
    state: present

- name: Enable one-context and network services for 8
  service:
    name: "{{ item }}"
    enabled: true
  loop:
    - one-context
    - network
  when: ansible_facts['distribution_major_version'] == '8'

- name: Enable one-context services for 9
  service:
    name: one-context
    enabled: true
  when: ansible_facts['distribution_major_version'] == '9'

- name: Install disk resize dependencies
  package:
    name:
      - cloud-utils-growpart
      - parted
    state: latest

- name: Regenerate the initramfs
  command: dracut -f --regenerate-all
