---
- name: Installing the system release files
  ansible.builtin.command: rpm --root=/rootfs --nodeps -ivh https://repo.almalinux.org/almalinux/almalinux-release-latest-9.aarch64.rpm
  args:
    warn: false
  changed_when: true

- name: Installing the system GPG keys
  ansible.builtin.command: rpm --root=/rootfs --nodeps -ivh https://repo.almalinux.org/almalinux/almalinux-gpg-keys-latest-9.aarch64.rpm
  args:
    warn: false
  changed_when: true

- name: Installing the system repos
  ansible.builtin.command: rpm --root=/rootfs --nodeps -ivh https://repo.almalinux.org/almalinux/almalinux-repos-latest-9.aarch64.rpm
  args:
    warn: false
  changed_when: true

- name: Update the system
  ansible.builtin.command: dnf -y --installroot=/rootfs --nogpgcheck upgrade
  args:
    warn: false
  changed_when: true

- name: Creating fstab
  ansible.builtin.template:
    src: templates/fstab.j2
    dest: /rootfs/etc/fstab
    mode: "0644"

- name: Install Base System on chroot
  ansible.builtin.shell: >
    dnf -y --installroot=/rootfs --nogpgcheck install
    kernel-core dracut-config-generic grub2-efi-aa64
    efibootmgr shim-aa64 chrony dhcp-client
    rng-tools NetworkManager-cloud-setup
    @core
    --exclude="kexec-tools"
    --exclude="biosdevname"
    --exclude="open-vm-tools"
    --exclude="rhn*"
    --exclude="iprutils"
    --exclude="iwl*-firmware"
    --exclude="dnf-plugin-spacewalk"
    --exclude="plymouth*"
    --exclude="dracut-config-rescue"
    --exclude="mdadm"
    --exclude="langpacks-*"
  changed_when: true

- name: Make sure RPM using SQLite backend
  ansible.builtin.command: rpm --root=/rootfs -E "%{_db_backend}"
  args:
    warn: false
  register: rpm_db_backend
  failed_when: "rpm_db_backend.stdout != 'sqlite'"
  changed_when: true

- name: Set default target/runlevel and disable tmp.mount
  ansible.builtin.command: chroot /rootfs systemctl {{ item.cmd }} {{ item.unit }}
  loop:
    - { cmd: "set-default", unit: "multi-user.target" }
    - { cmd: "mask", unit: "tmp.mount" }
  changed_when: true

- name: Set default locale to C.UTF-8
  ansible.builtin.copy:
    content: LANG=C.UTF-8
    dest: /rootfs/etc/locale.conf
    mode: 0644
