---
- name: Remove firewall and linux-firmware
  dnf:
    name:
      - firewalld
      - firewalld-filesystem
      - ipset
      - ipset-libs
      - iptables
      - python3-firewall
      - python3-slip
      - libnftnl
      - libnfnetlink
      - linux-firmware
    state: absent

- name: Install additional software
  dnf:
    name:
      - cockpit-system
      - cockpit-ws
      - dnf-utils
      - gdisk
      - nfs-utils
      - rsync
      - tar

- name: Find persistent-net.rules
  find:
    paths: /etc/udev/rules.d
    patterns: 70*
  register: net_rules

- name: Delete persistent-net.rules
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ net_rules.files }}"

- name: Configure /etc/sysconfig/network
  lineinfile:
    path: /etc/sysconfig/network
    line: "{{ item }}"
  with_items:
    - NETWORKING=yes
    - NOZEROCONF=yes

- name: Configure /etc/sysconfig/network-scripts/ifcfg-eth0
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: "{{ item }}"
    create: true
    owner: root
    group: root
    mode: 0644
  with_items:
    - DEVICE="eth0"
    - BOOTPROTO="dhcp"
    - ONBOOT="yes"
    - TYPE="Ethernet"
    - USERCTL="yes"
    - PEERDNS="yes"
    - IPV6INIT="no"
    - PERSISTENT_DHCLIENT="1"

- name: Disable consistent network device naming
  file:
    src: /dev/null
    dest: /etc/udev/rules.d/80-net-name-slot.rules
    owner: root
    group: root
    state: link

- name: Disable virtual terminals allocation by logind
  replace:
    path: '/etc/systemd/logind.conf'
    regexp: '^#?NAutoVTs=\d+'
    replace: 'NAutoVTs=0'

- name: Configure dhclient
  lineinfile:
    path: /etc/dhcp/dhclient.conf
    line: "{{ item }}"
  with_items:
    - 'timeout 300;'
    - 'retry 60;'

- name: Set infra yum variable to 'genclo'
  replace:
    path: /etc/yum/vars/infra
    regexp: '^(.*?)$'
    replace: 'genclo'

- name: Set default kernel package type to kernel
  replace:
    path: /etc/sysconfig/kernel
    regexp: '^(DEFAULTKERNEL=).*$'
    replace: '\1kernel'

- name: Add almalinux user to /etc/sudoers
  lineinfile:
    path: /etc/sudoers
    line: "almalinux\tALL=(ALL)\tNOPASSWD: ALL"
    state: present

# TODO: uncomment this when issue with Ansible tmp files is fixed
# - name: Disable root login
#   user:
#     name: root
#     password: '!!'
