---
- name: Remove firewall and linux-firmware
  dnf:
    name:
      - firewalld
      - firewalld-filesystem
      - ipset
      - ipset-libs
      - iptables
      - python3-firewall
      - python3-slip
      - libnftnl
      - libnfnetlink
      - linux-firmware
    state: absent

- name: Install additional software
  dnf:
    name:
      - cockpit-system
      - cockpit-ws
      - dnf-utils
      - gdisk
      - nfs-utils
      - rsync
      - tar
      - tuned
      - tcpdump

- name: Find persistent-net.rules
  find:
    paths: /etc/udev/rules.d
    patterns: 70*
  register: net_rules

- name: Delete persistent-net.rules
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ net_rules.files }}"

- name: Configure /etc/sysconfig/network
  lineinfile:
    path: /etc/sysconfig/network
    line: "{{ item }}"
  with_items:
    - NETWORKING=yes
    - NOZEROCONF=yes

- name: Configure /etc/sysconfig/network-scripts/ifcfg-eth0
  copy:
    src: ifcfg-eth0
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    owner: root
    group: root
    mode: '0644'

- name: Disable consistent network device naming
  file:
    src: /dev/null
    dest: /etc/udev/rules.d/80-net-name-slot.rules
    owner: root
    group: root
    state: link

- name: Disable virtual terminals allocation by logind
  replace:
    path: '/etc/systemd/logind.conf'
    regexp: '^#?NAutoVTs=\d+'
    replace: 'NAutoVTs=0'

- name: Configure NetworkManager default DHCP timeout
  community.general.ini_file:
    path: /etc/NetworkManager/conf.d/dhcp.conf
    section: connection
    option: ipv4.dhcp-timeout
    value: 300
    owner: root
    group: root
    mode: 0644
    seuser: system_u

- name: Set default kernel package type to kernel
  replace:
    path: /etc/sysconfig/kernel
    regexp: '^(DEFAULTKERNEL=).*$'
    replace: '\1kernel'

- name: Set virtual-guest as default profile for tuned
  lineinfile:
    path: /etc/tuned/active_profile
    line: virtual-guest
    create: yes

- name: Regenerate the initramfs
  command: dracut -f --regenerate-all

- name: Add almalinux user to /etc/sudoers
  lineinfile:
    path: /etc/sudoers
    line: "almalinux\tALL=(ALL)\tNOPASSWD: ALL"
    state: present

- name: Disable root login
  user:
    name: root
    password: '!!'
