---
- name: AlmaLinux Amazon AMI Stage 2
  hosts: "_chroot"
  become: true

  tasks:
    - name: Install AWS Systems Manager Agent (SSM Agent)
      ansible.builtin.dnf:
        name: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
        state: present


    - name: Delete DNF cache
      ansible.builtin.command: dnf clean all
      changed_when: true

    - name: Add IPv6 Support
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-eth0
        insertafter: '^IPV6INIT'
        line: 'IPV6_FAILURE_FATAL=no'
        state: present


    - name: Fix SELinux contexts
      ansible.builtin.command: chcon -t {{ item.setype }} {{ item.target }}
      changed_when: true
      loop:
        - { setype: 'etc_t', target: '/etc/sysconfig/network' }
        - { setype: 'net_conf_t', target: '/etc/sysconfig/network-scripts/ifcfg*' }
        - { setype: 'etc_t', target: '/etc/fstab' }
        - { setype: 'etc_t', target: '/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg' }
        - { setype: 'bootloader_etc_t', target: '/etc/default/grub' }
        - { setype: 'boot_t', target: '/boot/grub2/grub.cfg-bkup' }
        - { setype: 'initrc_exec_t', target: '/etc/rc.d/rc.local.vmimport' }


    - name: Remove ec2-user Cloud user
      ansible.builtin.user:
        name: ec2-user
        state: absent
        force: true


    - name: Find vmimport lefovers
      ansible.builtin.find:
        paths:
          - /etc/sysconfig/network-scripts
        patterns: 'vmimport*'
        file_type: any
        hidden: true
      register: vmimport_leftover


    - name: Find Cloud-init leftovers
      ansible.builtin.find:
        paths:
          - /var/lib/cloud/instances
        patterns: '*'
        file_type: any
        hidden: true
      register: cloudinit_leftover

    - name: Remove vmimport leftovers
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ vmimport_leftover.files }}"


    - name: Remove Cloud-init leftovers
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ cloudinit_leftover.files }}"


    - name: Remove leftovers from the system
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/cloud/cloud.cfg.d/vmimport.99-disable-network-config.cfg
        - /tmp
        - /var/tmp
        - /var/log/tuned
        - /var/lib/cloud
        - /var/log/amazon
        - /etc/machine-info
        - /var/lib/systemd/credential.secret
        - /var/lib/systemd/random-seed


    - name: Find log files
      ansible.builtin.find:
        file_type: file
        paths:
          - /var/log
          - /var/log/sssd
        patterns: '*.log, *.old, *.log.gz, *.[0-9], *.gz, *-????????'
      register: log_files


    - name: Remove log files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ log_files.files }}"


    - name: Find sudoers files created by AWS VM Import/Export
      ansible.builtin.find:
        file_type: file
        paths:
          - /etc/sudoers.d/
        patterns: '*'
      register: sudoers_files


    - name: Remove found sudoers files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ sudoers_files.files }}"


    - name: Truncate files
      ansible.builtin.command: "truncate -s 0 {{ item }}"
      changed_when: true
      loop:
        - /etc/machine-id
        - /etc/hostname
        - /etc/resolv.conf
        - /var/log/audit/audit.log
        - /var/log/wtmp
        - /var/log/lastlog
        - /var/log/btmp
        - /var/log/cron
        - /var/log/maillog
        - /var/log/messages
        - /var/log/secure
        - /var/log/spooler
