# An Ansible playbook that configures an AlmaLinux OS Azure image
---
- name: AlmaLinux Azure
  hosts: default
  become: true

  roles:
    - role: unified_boot
      when: is_unified_boot is defined
    - azure_guest
    - cleanup_vm
