# An Ansible playbook that configures a DigitalOcean image
---
- name: AlmaLinux DigitalOcean Image
  hosts: default
  become: true

  roles:
    - role: unified_boot
      when: is_unified_boot is defined
    - digitalocean_guest
    - cleanup_vm
