# An Ansible playbook that configures a Generic Cloud (OpenStack) image
---
- name: AlmaLinux Generic Cloud
  hosts: default
  become: true

  roles:
    - role: unified_boot
      when: is_unified_boot is defined
    - gencloud_guest
    - cleanup_vm
