# An Ansible playbook that configures a OpenNebula image
---
- name: AlmaLinux OpenNebula
  hosts: default
  become: true

  roles:
    - role: unified_boot
      when: is_unified_boot is defined
    - opennebula_guest
    - cleanup_vm
