# An Ansible playbook that configures Vagrant and VirtualBox support
---
- name: 'AlmaLinux Vagrant VirtualBox'
  hosts: default
  become: true
  
  roles:
    - upgrade_and_reboot
    - ezamriy.vbox_guest
    - install_vagrant_key
    - cleanup_vm
