---
galaxy_info:
  author: AlmaLinux OS Cloud SIG
  description: Unify bootloader configuration for BIOS and UEFI support
  company: AlmaLinux OS Foundation
  license: GPL-3.0-only
  min_ansible_version: 2.13.9
  galaxy_tags:
    - unifiedboot
    - bios
    - uefi
