---
- name: Disable SSH reverse DNS lookup
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "(.*UseDNS.*)"
    line: "UseDNS no"
    backrefs: true
    state: present
    create: false

- name: Install additional packages
  ansible.builtin.dnf:
    name:
      - cifs-utils
      - jq
      - nfs-utils
      - rsync
      - tcpdump
      - tuned
    state: present

- name: Install Vagrant public SSH key
  ansible.posix.authorized_key:
    user: vagrant
    key: https://raw.githubusercontent.com/hashicorp/vagrant/main/keys/vagrant.pub
    state: present
