---
# tasks file for configuring bootloader
- name: Configuring GRUB
  ansible.builtin.copy:
    src: /etc/default/grub
    dest: /rootfs/etc/default/grub
    mode: '0644'

- name: Creating GRUB config
  ansible.builtin.command: chroot /rootfs grub2-mkconfig -o /etc/grub2-efi.cfg
  changed_when: true
