name: Hyper-V Image Build

on:
  workflow_dispatch:
      inputs:

        date_time_stamp:
          description: 'Custom date+time stamp, YYYYMMDDhhmmss'
          required: false
          default: ''

        version_major:
          description: 'AlmaLinux major version'
          required: true
          default: '10'
          type: choice
          options:
            - 10-kitten
            - 10
            - 9
            - 8

        store_as_artifact:
          description: "Store images to the workflow Artifacts"
          required: true
          type: boolean
          default: false

        upload_to_s3:
          description: "Upload to S3 Bucket"
          required: true
          type: boolean
          default: true

        notify_mattermost:
          description: "Send notification to Mattermost"
          required: true
          type: boolean
          default: true
env:
  PACKER_GITHUB_API_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}

jobs:
  init-data:
    name: Initialize common data
    runs-on: ubuntu-24.04
    outputs:
      time_stamp: ${{ steps.date-time-stamp.outputs.time_stamp }}
      date_stamp: ${{ steps.date-time-stamp.outputs.date_stamp }}
    steps:
      - name: Date+time stamp
        id: date-time-stamp
        run: |
          # date+time stamp, YYYYMMDDhhmmss
          if [ "${{ inputs.date_time_stamp }}" != "" ]; then
            date_time_stamp="${{ inputs.date_time_stamp }}"
          else
            date_time_stamp=$(date -u '+%Y%m%d%H%M%S')
          fi
          echo "time_stamp=${date_time_stamp}" >> $GITHUB_OUTPUT

          # date stamp, YYYYMMDD
          date_stamp=${date_time_stamp:0:-6}
          echo "date_stamp=${date_stamp}" >> "$GITHUB_OUTPUT"

  build-gh-hosted:
    name: ${{ matrix.variant }} hyperv-x86_64 image
    permissions:
      id-token: write
      contents: read
    needs: [init-data]
    # use runs-on runners if within the almalinux org, otherwise GH runners
    runs-on: >-
      ${{
        github.repository_owner == 'AlmaLinux' &&
          format('runs-on={0}/family=c7i.metal-24xl+c7a.metal-48xl+*8gd.metal*/image=ubuntu24-full-x64', github.run_id)
        ||
        'ubuntu-24.04'
      }}
    strategy:
      fail-fast: false
      matrix:
        variant: >-
          ${{ fromJSON(
            ( inputs.version_major == '10-kitten' || inputs.version_major == '10' )
              && format('["{0}", "{0}-v2"]', inputs.version_major)
              || format('["{0}"]', inputs.version_major)
          ) }}

    env:
      TIME_STAMP: ${{ needs.init-data.outputs.time_stamp }}
      DATE_STAMP: ${{ needs.init-data.outputs.date_stamp }}

    steps:
      - name: Checkout ${{ github.action_repository }}
        uses: actions/checkout@v6

      - uses: ./.github/actions/shared-steps
        name: ${{ matrix.variant }} hyperv-x86_64 image
        with:
          type: hyperv
          variant: ${{ matrix.variant }}
          arch: x86_64
          S3_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_CHANNEL: ${{ vars.MATTERMOST_CHANNEL }}
          store_as_artifact: ${{ inputs.store_as_artifact }}
          upload_to_s3: ${{ inputs.upload_to_s3 }}
          notify_mattermost: ${{ inputs.notify_mattermost }}
          run_test: 'false'
          runner: ${{ github.repository_owner == 'AlmaLinux' && 'aws-ec2' || 'gh_hosted' }}
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
